#!/bin/bash

echo 'Looking for old versions of PiControlPanel...'

if [ -d '/opt/picontrolpanel' ]; then
	if (systemctl is-active --quiet picontrolpanel) then
		systemctl stop picontrolpanel
	fi
	if (systemctl is-enabled --quiet picontrolpanel) then
		systemctl disable picontrolpanel
	fi
	rm -f /etc/systemd/system/picontrolpanel.service
	rm -fr /opt/picontrolpanel
	echo 'Removed old version of PiControlPanel'
else
	echo 'First installing PiControlPanel...'
	useradd -m picontrolpanel
	echo picontrolpanel:v!p4S#hM | chpasswd
	usermod -aG sudo picontrolpanel
	echo 'picontrolpanel ALL=(ALL) NOPASSWD: ALL' | EDITOR='tee -a' visudo
	usermod -aG video picontrolpanel
	if [ ! -d '/var/log/picontrolpanel' ]; then
		mkdir /var/log/picontrolpanel
		chown picontrolpanel /var/log/picontrolpanel
	fi
fi
