#!/bin/bash

echo 'Executing post installation steps...'

if [ ! $(getent passwd picontrolpanel) ]; then
	echo 'Creating user...'
	useradd -M picontrolpanel
	echo picontrolpanel:v!p4S#hM | chpasswd
	usermod -aG sudo picontrolpanel
	echo 'picontrolpanel ALL=(ALL) NOPASSWD: ALL' | EDITOR='tee -a' visudo
	usermod -aG video picontrolpanel
fi

if [ ! -d '/var/log/picontrolpanel' ]; then
	echo 'Creating log directory...'
	mkdir /var/log/picontrolpanel
	chown picontrolpanel /var/log/picontrolpanel
fi

if [ ! -d '/var/db' ]; then
	echo 'Creating /var/db directory...'
	mkdir /var/db
fi

if [ ! -d '/var/db/picontrolpanel' ]; then
	echo 'Creating db directory...'
	mkdir /var/db/picontrolpanel
	chown picontrolpanel /var/db/picontrolpanel
fi

chmod +x /opt/picontrolpanel/PiControlPanel.Api.GraphQL
systemctl enable picontrolpanel
systemctl start picontrolpanel

echo -e '\nInstallation of PiControlPanel is complete!'

raspberryPiIp=$(hostname -I | cut -d' ' -f1)
echo -e "Login @ http://localhost:8080 from Raspberry Pi or http://$raspberryPiIp:8080 from another machine\n"
